### ISSUE TITLE
`bash-env` returns arity mismatch error

### ISSUE THREAD

**Issue by asumbek** [tesujimath/bash-env-elvish#7]
```
Exception: arity mismatch: assignment right-hand-side must be 1 value, but is 0 values
  /home/komo/.local/share/elvish/lib/github.com/tesujimath/bash-env-elvish/bash-env.elv:18:3-40:   var raw = (echo $raw-text | from-json)
  /home/komo/.config/elvish/rc.elv:5:1-67: bash-env:bash-env < ~/.nix-profile/etc/profile.d/hm-session-vars.sh
```

`elvish -version`: `0.21.0`, installed via Nix on Nixpkgs unstable channel.

**Comment by tesujimath** [comment]
What is `bash-env-json --version`?

If less than 0.9.1 please upgrade that and try again. 

Otherwise I will have to look into this further.

**Comment by tesujimath** [comment]
Also what commit are you on with bash-env-elvish? (Go into epm install directory and use `git log`)

**Comment by asumbek** [comment]
Seems like I didn't install `bash-env-json` properly, I'll be closing this issue.

**Comment by tesujimath** [comment]
@mbekkomo Thanks for the report, I improved the error message in case `bash-env-json` not found.
